[package]
name = "ui"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Abhinandh S <abhinandhsuby@proton.me>"]
license = "MIT"
description = "Personal UI Components."
repository = "https://github.com/abhinandh-s/typst-ui-kit"
keywords = []
categories = []
exclude = [ "examples/*", "tests/*" ]
