name: Tests

on:
  #push:
    #branches: [ "master" ]
  #pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_BACK: "true"
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Run unit test assertions
        run: |
          typst compile --root . tests/add-test.typ test-out.pdf