name: Local Action Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        
      - name: Setup Typst
        uses: typst-community/setup-typst@v5
        # abhinandh-s/typst-ui-kit@master
      - uses: ﻿./
  
      - name: Test import
        run: |
          typst compile - output.pdf << 'EOF'
          #import "@local/ui:0.1.0": add
          #assert(add(1, 2) == 3)
          EOF
